import { writeFileSync } from "node:fs";
import { allFaqs, faqGroups, findFaqs } from "./faq-content.mjs";

const products = [
  { slug: "cassava-peel-flour", name: "Cassava Peel Flour", category: "feed", categoryLabel: "Animal Feed Ingredient", image: "cassava-peel-flour.webp", description: "A processed cassava by-product supplied as an ingredient for animal feed applications.", overview: "Patrick Stone Ventures dries and hammer-mills cassava peels into a fine product supplied to small and large feed mills. The process creates a productive commercial use for material that can otherwise present a waste-management challenge around cassava processing facilities.", applications: ["Fish feed formulation", "Poultry feed formulation", "Feed milling operations"], customers: ["Feed mills", "Livestock feed producers", "Agricultural distributors"] },
  { slug: "cassava-peel-grits", name: "Cassava Peel Grits", category: "feed", categoryLabel: "Animal Feed Ingredient", image: "cassava-processing.webp", description: "Coarse processed cassava peel material supplied for animal feed applications.", overview: "Cassava peel grits—also described as cassava peel coarse—are produced from cassava processing by-products and supplied to feed businesses in Nigeria and the wider West African market.", applications: ["Animal feed formulation", "Feed ingredient blending", "Livestock feed production"], customers: ["Feed mills", "Livestock feed producers", "Commodity buyers"] },
  { slug: "cassava-flour", name: "Cassava Flour", category: "cassava", categoryLabel: "Cassava Product", image: "cassava-flour.webp", description: "Processed cassava flour available for suitable commercial requirements.", overview: "Patrick Stone Ventures trades cassava flour for business buyers. Current grades, applications and technical specifications are confirmed against each buyer’s requirement.", applications: ["Commercial processing", "Food value-chain requirements", "Industrial requirements, subject to specification"], customers: ["Food processors", "Agricultural distributors", "Industrial buyers"] },
  { slug: "cassava-starch", name: "Cassava Starch", category: "cassava", categoryLabel: "Cassava Product", image: "cassava-flour.webp", description: "Cassava-derived starch sourced for commercial and industrial buyers.", overview: "Cassava starch forms part of the company’s agricultural commodity offering. Buyers can contact the sales team for current grade, availability, packaging and supply information.", applications: ["Commercial processing", "Food value-chain requirements", "Industrial requirements, subject to specification"], customers: ["Food processors", "Industrial processors", "Commodity buyers"] },
  { slug: "soybean-cake", name: "Soybean Cake", category: "feed", categoryLabel: "Animal Feed Ingredient", image: "soybean-cake.webp", description: "Soybean cake or meal sourced for feed mills and commercial buyers.", overview: "Patrick Stone Ventures sources and supplies soybean cake as part of its agricultural commodity trading activity. Specifications and availability are provided in response to current requirements.", applications: ["Animal feed formulation", "Feed milling operations", "Ingredient distribution"], customers: ["Feed mills", "Livestock feed producers", "Agricultural distributors"] },
  { slug: "palm-kernel-cake", name: "Palm Kernel Cake", category: "feed", categoryLabel: "Animal Feed Ingredient", image: "palm-kernel-cake.webp", description: "Palm kernel cake supplied as an agricultural feed ingredient.", overview: "Palm kernel cake is included in Patrick Stone Ventures’ commodity trading portfolio for feed-sector buyers. Contact the sales team for current product and supply information.", applications: ["Animal feed formulation", "Feed milling operations", "Ingredient distribution"], customers: ["Feed mills", "Livestock feed producers", "Commodity buyers"] },
  { slug: "maize", name: "Maize", category: "commodity", categoryLabel: "Agricultural Commodity", image: "commodity-supply.webp", description: "Maize sourced and supplied for commercial agricultural value chains.", overview: "Patrick Stone Ventures trades maize alongside its feed ingredients and cassava products. Supply discussions are matched to the buyer’s intended use, location and current requirement.", applications: ["Feed production", "Commercial processing", "Commodity distribution"], customers: ["Feed mills", "Food processors", "Agricultural distributors"] }
];

const faqSchema = faqs => faqs?.length ? `\n  <script type="application/ld+json">${JSON.stringify({
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map(([question, answer]) => ({
    "@type": "Question",
    name: question,
    acceptedAnswer: { "@type": "Answer", text: answer }
  }))
})}</script>` : "";

const head = ({ title, description, path, image = "hero-cassava-processing.webp", schema = "WebPage", faqs = [] }) => `
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${title}</title>
  <meta name="description" content="${description}">
  <meta name="theme-color" content="#173f35">
  <meta property="og:type" content="website">
  <meta property="og:title" content="${title}">
  <meta property="og:description" content="${description}">
  <meta property="og:url" content="https://patrickstoneventures.com.ng/${path}">
  <meta property="og:image" content="https://patrickstoneventures.com.ng/assets/images/${image}">
  <link rel="canonical" href="https://patrickstoneventures.com.ng/${path}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&amp;family=DM+Serif+Display&amp;display=swap" rel="stylesheet">
  <link rel="stylesheet" href="assets/css/style.css">
  <link rel="stylesheet" href="assets/css/responsive.css">
  <script type="application/ld+json">{"@context":"https://schema.org","@type":"${schema}","name":"${title}","url":"https://patrickstoneventures.com.ng/${path}","isPartOf":{"@type":"WebSite","name":"Patrick Stone Ventures Limited","url":"https://patrickstoneventures.com.ng/"}}</script>${faqSchema(faqs)}
</head>`;

const header = (active = "") => `
<a class="skip-link" href="#main-content">Skip to content</a>
<header class="site-header" data-header><div class="nav-shell">
  <a class="brand" href="index.html" aria-label="Patrick Stone Ventures home"><img src="assets/images/patrick-stone-logo.webp" width="242" height="75" alt="Patrick Stone Ventures Limited"></a>
  <button class="menu-toggle" type="button" aria-label="Open navigation" aria-expanded="false" aria-controls="primary-navigation" data-menu-toggle><span></span><span></span><span></span></button>
  <nav class="primary-nav" id="primary-navigation" aria-label="Primary navigation" data-menu><ul class="nav-list">
    <li><a ${active === "home" ? 'class="is-current"' : ""} href="index.html">Home</a></li>
    <li><a ${active === "about" ? 'class="is-current"' : ""} href="about.html">About Us</a></li>
    <li class="has-dropdown"><button class="dropdown-toggle" type="button" aria-expanded="false">What We Do <span aria-hidden="true">⌄</span></button><ul class="dropdown-menu"><li><a href="cassava-processing.html">Cassava Processing</a></li><li><a href="greenhouse.html">Greenhouse Solutions</a></li><li><a href="commodity-trading.html">Commodity Trading</a></li><li><a href="impact.html">Impact &amp; Sustainability</a></li><li><a href="services.html">All Services</a></li></ul></li>
    <li class="has-dropdown"><button class="dropdown-toggle" type="button" aria-expanded="false">Products <span aria-hidden="true">⌄</span></button><ul class="dropdown-menu dropdown-menu-wide">${products.map(p => `<li><a href="product-${p.slug}.html">${p.name}</a></li>`).join("")}<li><a href="products.html">View All Products</a></li></ul></li>
    <li><a ${active === "faq" ? 'class="is-current"' : ""} href="faq.html">FAQs</a></li>
    <li><a ${active === "contact" ? 'class="is-current"' : ""} href="contact.html">Contact</a></li>
  </ul><button class="button button-small nav-cta" type="button" data-quote-open>Request a quote</button></nav>
</div></header>`;

const footer = () => `
<footer class="site-footer"><div class="container footer-grid">
  <div class="footer-brand"><a href="index.html"><img src="assets/images/patrick-stone-logo-white.webp" alt="Patrick Stone Ventures Limited" width="242" height="75"></a><p>A modern agribusiness and agricultural solutions company transforming resources into commercially valuable products.</p><a class="footer-external" href="https://greenhouse.ng/" target="_blank" rel="noopener">Visit Greenhouse.ng ↗</a></div>
  <div><h2>Company</h2><ul><li><a href="about.html">About Us</a></li><li><a href="impact.html">Impact &amp; Sustainability</a></li><li><a href="services.html">What We Do</a></li><li><a href="faq.html">FAQs</a></li><li><a href="contact.html">Contact</a></li></ul></div>
  <div><h2>Business</h2><ul><li><a href="cassava-processing.html">Cassava Processing</a></li><li><a href="commodity-trading.html">Commodity Trading</a></li><li><a href="greenhouse.html">Greenhouse Solutions</a></li><li><a href="products.html">Products</a></li></ul></div>
  <div><h2>Contact</h2><address>7 Ibiyinka Olorunbe Street<br>Victoria Island, Lagos<br>Nigeria</address><ul class="footer-contact"><li><a href="mailto:sales@patrickstoneventures.com.ng">sales@patrickstoneventures.com.ng</a></li><li><a href="tel:+2348167525393">+234 816 752 5393</a></li></ul></div>
</div><div class="container footer-bottom"><p>© <span data-year></span> Patrick Stone Ventures Limited. All rights reserved.</p><p>Agriculture · Processing · Infrastructure</p></div></footer>
<a class="whatsapp-button" href="https://wa.me/2348167525393?text=Hello%20Patrick%20Stone%20Ventures%2C%20I%20would%20like%20to%20enquire%20about%20your%20products%2Fservices." target="_blank" rel="noopener" aria-label="Enquire on WhatsApp"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16 3a12 12 0 0 0-10.4 18l-1.5 5.5 5.7-1.5A12 12 0 1 0 16 3Zm0 21.8c-2 0-3.8-.6-5.4-1.6l-.4-.2-3.4.9.9-3.3-.2-.4A9.8 9.8 0 1 1 16 24.8Zm5.4-7.3c-.3-.1-1.8-.9-2-.9-.3-.1-.5-.1-.7.2l-1 1.2c-.2.2-.4.2-.7.1-2-.8-3.4-2.4-4-3.5-.2-.3 0-.5.1-.7l.5-.6c.2-.2.2-.4.3-.6.1-.2 0-.5 0-.7l-.9-2c-.2-.6-.5-.5-.7-.5h-.6c-.2 0-.6.1-.9.4-.3.4-1.2 1.2-1.2 2.9s1.2 3.3 1.4 3.5c.2.2 2.4 3.7 5.9 5.2.8.4 1.5.6 2 .7.8.3 1.6.2 2.2.1.7-.1 1.8-.7 2.1-1.4.3-.7.3-1.3.2-1.4-.2-.2-.4-.3-.8-.5Z"/></svg></a>
<button class="back-to-top" type="button" aria-label="Back to top" data-back-top>↑</button>
<div class="modal" role="dialog" aria-modal="true" aria-labelledby="quote-title" aria-hidden="true" data-quote-modal><div class="modal-backdrop" data-quote-close></div><div class="modal-panel" role="document"><button class="modal-close" type="button" aria-label="Close quote form" data-quote-close>×</button><p class="eyebrow">Business enquiry</p><h2 id="quote-title">Request a quote.</h2><p>Tell us what you need. Our team can follow up with current specifications, availability and supply options.</p>
<!-- Form integration point: replace # with a Formspree, Web3Forms or custom endpoint. -->
<form class="quote-form" action="#" method="post" data-static-form><div class="form-grid"><label>Full name<input type="text" name="name" autocomplete="name" required></label><label>Company name<input type="text" name="company" autocomplete="organization"></label><label>Email<input type="email" name="email" autocomplete="email" required></label><label>Phone / WhatsApp<input type="tel" name="phone" autocomplete="tel" required></label><label>Country<input type="text" name="country" autocomplete="country-name"></label><label>Product / service<select name="product" data-product-select required><option value="">Select an option</option>${products.map(p => `<option>${p.name}</option>`).join("")}<option>Greenhouse Construction</option><option>Other</option></select></label><label>Estimated quantity<input type="text" name="quantity" placeholder="If known"></label><label>Delivery location<input type="text" name="delivery_location"></label></div><label>Message<textarea name="message" rows="4" placeholder="Describe your requirement"></textarea></label><button class="button button-dark" type="submit">Send quote request</button><p class="form-note" aria-live="polite" data-form-note></p></form></div></div>
<script src="assets/js/main.js" defer></script>`;

const page = ({ meta, active, main }) => `<!doctype html><html lang="en">${head(meta)}<body>${header(active)}<main id="main-content">${main}</main>${footer()}</body></html>\n`;
const hero = (eyebrow, title, copy, image) => `<section class="inner-hero" style="--hero-image:url('../images/${image}')"><div class="container"><div class="breadcrumb"><a href="index.html">Home</a> / ${title}</div><p class="eyebrow eyebrow-light">${eyebrow}</p><h1>${title}</h1><p>${copy}</p></div></section>`;
const band = (title, copy, product = "") => `<section class="band-cta"><div class="container"><div><h2>${title}</h2><p>${copy}</p></div><button class="button" type="button" data-quote-open${product ? ` data-product="${product}"` : ""}>Request a quote</button></div></section>`;
const faqList = faqs => `<div class="faq-list">${faqs.map(([question, answer]) => `<article class="faq-item"><h3><button class="faq-question" type="button" aria-expanded="false" data-faq-question>${question}<span aria-hidden="true">+</span></button></h3><div class="faq-answer"><p>${answer}</p></div></article>`).join("")}</div>`;
const faqSection = (title, faqs) => `<section class="section value-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">Frequently asked questions</p><h2>${title}</h2></div><a class="text-link" href="faq.html">View all FAQs →</a></div>${faqList(faqs)}</div></section>`;

const pageFaqs = {
  about: findFaqs("What is Patrick Stone Ventures Limited?", "What does Patrick Stone Ventures do?", "When did Patrick Stone Ventures begin cassava processing?", "Who does Patrick Stone Ventures supply?"),
  services: findFaqs("What does Patrick Stone Ventures do?", "Why work with Patrick Stone Ventures?", "What industries does Patrick Stone Ventures serve?"),
  cassava: findFaqs("Does Patrick Stone Ventures process cassava peels in Nigeria?", "How does Patrick Stone Ventures process cassava peels?", "What is the difference between cassava peel flour and cassava peel grits?", "Does Patrick Stone Ventures provide laboratory specifications for cassava peel products?"),
  commodities: findFaqs("What agricultural commodities does Patrick Stone Ventures supply?", "Is Patrick Stone Ventures an agricultural commodity supplier in Nigeria?", "Does Patrick Stone Ventures supply agricultural commodities in bulk?", "What information should I provide when requesting a commodity quotation?"),
  greenhouse: findFaqs("Does Patrick Stone Ventures build greenhouses?", "What is Greenhouse.ng?", "What greenhouse services does Patrick Stone Ventures provide?", "Can Patrick Stone Ventures provide irrigation systems with a greenhouse project?"),
  impact: findFaqs("How does Patrick Stone Ventures turn agricultural waste into value?", "Why is cassava peel processing important?", "Is Patrick Stone Ventures involved in circular agriculture?", "How does cassava peel processing support local communities?"),
  contact: findFaqs("How can I contact Patrick Stone Ventures?", "How do I request a quote from Patrick Stone Ventures?", "What information should I provide when requesting a commodity quotation?", "Does Patrick Stone Ventures supply customers outside Nigeria?")
};

const pages = {
  "about.html": page({ active: "about", meta: { title: "About Patrick Stone Ventures | Agribusiness Nigeria", description: "Learn about Patrick Stone Ventures, an agribusiness company active in cassava processing, commodity trading and greenhouse solutions.", path: "about.html", faqs: pageFaqs.about }, main: `
    ${hero("Our company", "Growing value across agriculture.", "We connect agricultural resources, commercial markets and productive infrastructure across Nigeria’s agricultural value chain.", "cassava-processing.webp")}
    <section class="section"><div class="container intro-grid"><div><p class="eyebrow">Who we are</p><h2>A practical agribusiness built for commercial value.</h2></div><div class="intro-copy"><p class="lead">Patrick Stone Ventures Limited is an agribusiness-focused company with interests in cassava processing, agricultural commodity trading and greenhouse solutions.</p><p>The business is an early mover in Nigeria’s cassava peel processing industry. From its first factory in Iseyin, it processes and supplies cassava peel flour and cassava peel grits to small and large feed mills in Nigeria and the West African sub-region.</p><p>Our greenhouse construction and installation activities operate through Greenhouse.ng, while our commodity activity connects feed ingredients and agricultural products with commercial buyers.</p><div class="statement">Transforming agricultural resources into commercially valuable products and solutions.</div></div></div></section>
    <section class="section founder-section"><div class="container founder-grid"><div><p class="eyebrow">Founder’s vision</p><div class="founder-id"><strong>Patrick Wak</strong><span>Founder, Patrick Stone Ventures</span></div></div><blockquote class="founder-quote">To create wealth from waste generated through agricultural processes—and create value in the communities where we operate.</blockquote></div></section>
    <section class="section section-dark"><div class="container"><p class="eyebrow eyebrow-light">Our story</p><h2>Experience rooted in the value chain.</h2><div class="timeline"><article><strong>2018</strong><p>The company established its first cassava peel processing factory in Iseyin.</p></article><article><strong>Today</strong><p>Cassava products and agricultural commodities are supplied to business buyers across the value chain.</p></article><article><strong>Across agriculture</strong><p>Greenhouse.ng extends the group’s work into protected agriculture and farm infrastructure.</p></article></div></div></section>
    <section class="section"><div class="container"><div class="section-heading"><div><p class="eyebrow">Our approach</p><h2>Principles that guide delivery.</h2></div></div><div class="approach-grid"><article><span>01</span><h3>Quality</h3><p>Attention to product suitability and service delivery.</p></article><article><span>02</span><h3>Innovation</h3><p>Applying appropriate technology to agricultural operations.</p></article><article><span>03</span><h3>Responsible Agriculture</h3><p>Converting agricultural by-products into useful products and reducing missed value.</p></article><article><span>04</span><h3>Partnership</h3><p>Understanding the commercial requirement behind every enquiry.</p></article><article><span>05</span><h3>Community Value</h3><p>Supporting work opportunities and participation around processing operations.</p></article></div><p style="margin-top:28px"><a class="text-link" href="impact.html">Explore our impact and sustainability vision →</a></p></div></section>
    ${faqSection("About our company.", pageFaqs.about)}
    ${band("Let’s build more value from agriculture.", "Discuss product supply, commodity sourcing or agricultural infrastructure with our team.")}` }),

  "services.html": page({ meta: { title: "Agricultural Services Nigeria | Patrick Stone Ventures", description: "Explore cassava processing, commodity supply, greenhouse construction, installation, irrigation and agronomy support.", path: "services.html", schema: "Service", faqs: pageFaqs.services }, main: `
    ${hero("What we do", "Integrated agricultural solutions.", "Processing, supply and protected-agriculture services designed around real commercial requirements.", "greenhouse-installation.webp")}
    <section class="section"><div class="container"><div class="section-heading"><div><p class="eyebrow">Our capabilities</p><h2>One company, connected agricultural expertise.</h2></div><p>Engage Patrick Stone Ventures for a focused requirement or a wider agricultural project.</p></div><div class="service-grid">
      <article class="service-card"><img src="assets/images/cassava-peel-flour.webp" alt="Cassava peel flour processing" loading="lazy"><div class="service-card-content"><h3>Cassava Processing</h3><p>Drying and milling cassava peels into flour and coarse grits for feed-value-chain applications.</p><a class="text-link" href="cassava-processing.html">Explore service →</a></div></article>
      <article class="service-card"><img src="assets/images/commodity-supply.webp" alt="Agricultural commodities in a warehouse" loading="lazy"><div class="service-card-content"><h3>Commodity Trading</h3><p>Sourcing and supplying feed ingredients, cassava products and maize.</p><a class="text-link" href="commodity-trading.html">Explore service →</a></div></article>
      <article class="service-card"><img src="assets/images/greenhouse-installation.webp" alt="Commercial greenhouse structure" loading="lazy"><div class="service-card-content"><h3>Greenhouse Design</h3><p>Planning greenhouse solutions around the intended crop, site and operating requirement.</p><a class="text-link" href="greenhouse.html">Explore service →</a></div></article>
      <article class="service-card"><img src="assets/images/greenhouse-interior.webp" alt="Crops growing under greenhouse protection" loading="lazy"><div class="service-card-content"><h3>Construction &amp; Installation</h3><p>Greenhouse structure construction and installation delivered through Greenhouse.ng.</p><a class="text-link" href="greenhouse.html">Explore service →</a></div></article>
      <article class="service-card"><img src="assets/images/greenhouse-interior.webp" alt="Irrigated greenhouse crops" loading="lazy"><div class="service-card-content"><h3>Irrigation &amp; Accessories</h3><p>Drip irrigation, covers, insect nets, profiles, zig-zag wires and related materials.</p><a class="text-link" href="greenhouse.html">Explore service →</a></div></article>
      <article class="service-card"><img src="assets/images/hero-cassava-processing.webp" alt="Agricultural team at work" loading="lazy"><div class="service-card-content"><h3>Agronomy Support</h3><p>Agronomy support, agricultural inputs and farm advisory through Greenhouse.ng.</p><a class="text-link" href="greenhouse.html">Explore service →</a></div></article>
      <article class="service-card"><img src="assets/images/cassava-processing.webp" alt="Cassava processing workers creating value from agricultural by-products" loading="lazy"><div class="service-card-content"><h3>Waste-to-Value</h3><p>Creating productive commercial uses for cassava peels while supporting value creation in operating communities.</p><a class="text-link" href="impact.html">Explore our impact →</a></div></article>
    </div></div></section>${faqSection("Our agricultural services.", pageFaqs.services)}${band("Have an agricultural requirement?", "Tell us what you need, where it is required and the intended commercial use.")}` }),

  "cassava-processing.html": page({ meta: { title: "Cassava Peel Processing Nigeria | Patrick Stone Ventures", description: "Cassava peel flour and cassava peel grits processing and supply for feed mills in Nigeria and West Africa.", path: "cassava-processing.html", image: "cassava-processing.webp", schema: "Service", faqs: pageFaqs.cassava }, main: `
    ${hero("Cassava value creation", "Cassava processing that creates commercial value.", "Turning a challenging agricultural by-product into useful ingredients for feed mills and livestock feed producers.", "cassava-processing.webp")}
    <section class="section"><div class="container media-split"><div class="media-frame"><img src="assets/images/cassava-peel-flour.webp" alt="Cassava peel flour being processed" loading="lazy"></div><div class="media-copy"><p class="eyebrow">Established in Iseyin</p><h2>An early mover in cassava peel processing.</h2><p class="lead">Patrick Stone Ventures began cassava peel processing operations with its first factory in Iseyin in 2018.</p><p>Cassava peels can accumulate around processing facilities in rural communities and become an environmental and waste-management concern. Our model gives that material a productive commercial route.</p><p>Today, the company processes and supplies cassava peel flour and cassava peel coarse or grits to small and large feed mills across Nigeria and the wider West African market.</p><ul class="check-list"><li>Cassava peel flour</li><li>Cassava peel grits</li><li>Potential use in fish and poultry feed formulations</li><li>Current specifications available on request</li></ul><a class="button button-dark" href="products.html">View cassava products</a></div></div></section>
    <section class="section value-section"><div class="container value-layout"><div class="value-copy"><p class="eyebrow">Processing workflow</p><h2>From by-product to useful ingredient.</h2><p>Collected cassava peels are dried before being crushed in hammer mills. This produces a fine flour or coarse grit that can be supplied for suitable feed applications.</p><p>Product suitability remains subject to the buyer’s formulation and current specification.</p></div><ol class="process-flow"><li><span>01</span><div><strong>Cassava peel collection</strong><small>Peels are gathered from cassava processing facilities.</small></div></li><li><span>02</span><div><strong>Preparation</strong><small>Material is prepared for controlled processing.</small></div></li><li><span>03</span><div><strong>Drying</strong><small>Moisture is reduced before milling.</small></div></li><li><span>04</span><div><strong>Hammer milling or grit production</strong><small>Prepared as fine flour or coarse grits.</small></div></li><li><span>05</span><div><strong>Packaging and supply</strong><small>Prepared for feed-value-chain buyers.</small></div></li></ol></div></section>
    <section class="section"><div class="container"><div class="section-heading"><div><p class="eyebrow">Value beyond the product</p><h2>A model designed to benefit communities.</h2></div><p>The founder’s vision connects resource recovery with enterprise and local work opportunities.</p></div><div class="impact-pillars"><article class="impact-pillar"><span>Resource</span><h3>A use for agricultural by-products</h3><p>Redirecting cassava peels toward productive processing instead of unmanaged accumulation.</p></article><article class="impact-pillar"><span>Enterprise</span><h3>New commercial value</h3><p>Creating saleable ingredients that connect cassava processors with feed-sector demand.</p></article><article class="impact-pillar"><span>Community</span><h3>Local participation</h3><p>Supporting gainful work opportunities for young people around collection and processing operations.</p></article></div><p style="margin-top:28px"><a class="text-link" href="impact.html">Read our impact vision →</a></p></div></section>
    ${faqSection("Cassava peel processing and products.", pageFaqs.cassava)}
    ${band("Source cassava peel products for your operation.", "Contact our sales team for current specifications, packaging options and availability.", "Cassava Peel Flour")}` }),

  "commodity-trading.html": page({ meta: { title: "Agricultural Commodity Trading Nigeria | Patrick Stone Ventures", description: "Reliable sourcing and supply of soybean cake, palm kernel cake, maize, cassava flour, starch and other agricultural commodities.", path: "commodity-trading.html", image: "commodity-supply.webp", schema: "Service", faqs: pageFaqs.commodities }, main: `
    ${hero("Sourcing and supply", "Reliable agricultural commodity supply.", "Connecting feed mills, processors, distributors and commercial buyers with agricultural commodities.", "commodity-supply.webp")}
    <section class="section"><div class="container intro-grid"><div><p class="eyebrow">Commodity trading</p><h2>Commercial supply built around your requirement.</h2></div><div class="intro-copy"><p class="lead">Patrick Stone Ventures trades agricultural commodities that support animal feed, food and wider agricultural value chains.</p><p>Our portfolio includes soybean cake, palm kernel cake, maize, cassava flour and cassava starch. Brewery waste or brewers dried grain may also be considered where appropriate and available.</p><p>Every enquiry is handled against current availability, location, quantity and the buyer’s intended use. Technical specifications are supplied on request rather than assumed.</p></div></div></section>
    <section class="section section-dark"><div class="container"><div class="section-heading section-heading-light"><div><p class="eyebrow eyebrow-light">How we work</p><h2>From requirement to delivery.</h2></div></div><div class="approach-grid"><article><span>01</span><h3>Requirement</h3><p>We clarify product, quantity, destination and timing.</p></article><article><span>02</span><h3>Sourcing</h3><p>Suitable commodity supply is identified against the enquiry.</p></article><article><span>03</span><h3>Aggregation</h3><p>Where required, supply is brought together for fulfilment.</p></article><article><span>04</span><h3>Supply</h3><p>Product and packaging details are confirmed with the buyer.</p></article><article><span>05</span><h3>Distribution</h3><p>Delivery requirements are agreed for the destination.</p></article></div></div></section>
    <section class="section"><div class="container"><div class="section-heading"><div><p class="eyebrow">Available commodities</p><h2>Products for commercial buyers.</h2></div><a class="text-link" href="products.html">View full catalogue →</a></div><div class="use-grid"><article class="use-card"><span>01</span><h3>Soybean Cake</h3><p>Feed ingredient supplied for commercial formulation requirements.</p></article><article class="use-card"><span>02</span><h3>Palm Kernel Cake</h3><p>Agricultural feed ingredient available to business buyers.</p></article><article class="use-card"><span>03</span><h3>Maize</h3><p>Commodity supply for feed, processing and distribution value chains.</p></article><article class="use-card"><span>04</span><h3>Cassava Flour</h3><p>Processed cassava product traded for commercial requirements.</p></article><article class="use-card"><span>05</span><h3>Cassava Starch</h3><p>Cassava-derived starch for suitable food or industrial requirements.</p></article><article class="use-card"><span>06</span><h3>Other Commodities</h3><p>Discuss current agricultural commodity needs with our team.</p></article></div></div></section>
    ${faqSection("Commodity sourcing and bulk supply.", pageFaqs.commodities)}
    ${band("Request a commodity supply quote.", "Share your product, expected quantity, delivery location and timing.")}` }),

  "greenhouse.html": page({ meta: { title: "Greenhouse Construction Nigeria | Patrick Stone Ventures", description: "Greenhouse design, kits, construction, installation, irrigation, accessories and agronomy support through Greenhouse.ng.", path: "greenhouse.html", image: "greenhouse-installation.webp", schema: "Service", faqs: pageFaqs.greenhouse }, main: `
    ${hero("Greenhouse.ng", "Modern protected agriculture solutions.", "Greenhouse infrastructure, materials and support delivered through a Patrick Stone Ventures business.", "greenhouse-installation.webp")}
    <section class="section"><div class="container media-split"><div class="media-frame"><img src="assets/images/greenhouse-interior.webp" alt="Healthy crops inside a modern greenhouse" loading="lazy"></div><div class="media-copy"><p class="eyebrow">A Patrick Stone Ventures business</p><h2>Infrastructure for productive protected farming.</h2><p class="lead">Greenhouse.ng is the greenhouse construction and agricultural infrastructure brand operated by Patrick Stone Ventures Limited.</p><p>The business constructs and installs greenhouses and supplies relevant materials, irrigation components, agricultural inputs and agronomy support.</p><ul class="check-list"><li>Greenhouse design and kits</li><li>Construction and installation</li><li>Drip irrigation</li><li>UV-treated greenhouse covers and insect nets</li><li>Profiles and zig-zag wires</li><li>Agricultural inputs and agronomy support</li></ul><a class="button" href="https://greenhouse.ng/" target="_blank" rel="noopener">Visit Greenhouse.ng ↗</a></div></div></section>
    <section class="section value-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">Greenhouse capabilities</p><h2>Support across the project lifecycle.</h2></div></div><div class="service-grid"><article class="service-card"><div class="service-card-content"><h3>Design</h3><p>Planning an appropriate protected-agriculture solution around project needs.</p></div></article><article class="service-card"><div class="service-card-content"><h3>Construction</h3><p>Greenhouse structures built and installed for agricultural operations.</p></div></article><article class="service-card"><div class="service-card-content"><h3>Irrigation</h3><p>Drip irrigation systems and associated components for greenhouse projects.</p></div></article><article class="service-card"><div class="service-card-content"><h3>Materials</h3><p>Covers, insect nets, profiles, wires and other greenhouse accessories.</p></div></article><article class="service-card"><div class="service-card-content"><h3>Agricultural Inputs</h3><p>Relevant inputs including seeds and crop-protection products.</p></div></article><article class="service-card"><div class="service-card-content"><h3>Agronomy Support</h3><p>Practical farm advisory and agronomy assistance through Greenhouse.ng.</p></div></article></div></div></section>
    ${faqSection("Greenhouse design and installation.", pageFaqs.greenhouse)}
    ${band("Planning a greenhouse project?", "Discuss your site, intended crop and infrastructure requirements with Greenhouse.ng.", "Greenhouse Construction")}` }),

  "products.html": page({ meta: { title: "Agricultural Products Nigeria | Patrick Stone Ventures", description: "Browse cassava products, animal feed ingredients and agricultural commodities supplied by Patrick Stone Ventures.", path: "products.html", image: "commodity-supply.webp" }, main: `
    ${hero("Product catalogue", "Agricultural products for business buyers.", "Cassava products, feed ingredients and agricultural commodities supplied for commercial requirements.", "commodity-supply.webp")}
    <section class="section"><div class="container"><div class="catalog-toolbar" aria-label="Filter products"><button class="filter-button is-active" type="button" data-filter="all">All Products</button><button class="filter-button" type="button" data-filter="cassava">Cassava Products</button><button class="filter-button" type="button" data-filter="feed">Animal Feed Ingredients</button><button class="filter-button" type="button" data-filter="commodity">Agricultural Commodities</button></div><div class="catalog-grid">${products.map(p => `<article class="product-card catalog-card" data-category="${p.category}"><a class="product-image" href="product-${p.slug}.html"><img src="assets/images/${p.image}" alt="${p.name}" loading="lazy"><span>${p.categoryLabel}</span></a><div class="product-body"><h3><a href="product-${p.slug}.html">${p.name}</a></h3><p>${p.description}</p><div><a class="text-link" href="product-${p.slug}.html">View product →</a><button class="quote-link" data-quote-open data-product="${p.name}">Request quote</button></div></div></article>`).join("")}</div></div></section>
    ${band("Need a product or commodity not listed?", "Tell our team what you are looking for and where it is required.")}` }),

  "impact.html": page({ meta: { title: "Impact & Sustainability | Patrick Stone Ventures", description: "See how Patrick Stone Ventures creates commercial and community value by processing cassava peels into useful feed ingredients.", path: "impact.html", image: "cassava-processing.webp", faqs: pageFaqs.impact }, main: `
    ${hero("Impact & sustainability", "Creating wealth from agricultural waste.", "A circular value model that connects cassava processing, feed supply and opportunity in the communities where we operate.", "cassava-processing.webp")}
    <section class="section founder-section"><div class="container founder-grid"><div><p class="eyebrow">Founder’s vision</p><div class="founder-id"><strong>Patrick Wak</strong><span>Founder, Patrick Stone Ventures</span></div></div><blockquote class="founder-quote">Our vision and mission are simple: to create wealth from waste generated through agricultural processes.</blockquote></div></section>
    <section class="section video-section" id="founder-video"><div class="container video-feature"><div class="video-copy"><p class="eyebrow">In the founder’s words</p><h2>See how the process creates value.</h2><p>Patrick Wak explains the cassava-peel challenge, the drying and milling process, and the opportunity to create useful products and work within operating communities.</p><a class="text-link" href="https://youtu.be/7H1BhtIHDXg" target="_blank" rel="noopener">Watch directly on YouTube ↗</a></div><div class="video-frame"><iframe src="https://www.youtube-nocookie.com/embed/7H1BhtIHDXg?rel=0" title="Patrick Stone Ventures founder explains the cassava peel processing and waste-to-value vision" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div></div></section>
    <section class="section"><div class="container"><div class="section-heading"><div><p class="eyebrow">The challenge and opportunity</p><h2>Value should not end with the cassava tuber.</h2></div><p>Cassava processing generates peels that can accumulate around facilities in rural communities if they do not have a productive outlet.</p></div><div class="impact-chain"><article><span>01</span><h3>Agricultural by-product</h3><p>Cassava peels emerge from processing activity and can become a local waste-management concern.</p></article><article><span>02</span><h3>Drying and milling</h3><p>The peels are collected, prepared, dried and processed through hammer mills.</p></article><article><span>03</span><h3>Useful ingredient</h3><p>The resulting flour or grits can serve suitable fish, poultry and wider feed formulations.</p></article><article><span>04</span><h3>Shared value</h3><p>Agricultural material gains commercial purpose while operations create local participation and work opportunities.</p></article></div></div></section>
    <section class="section value-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">Three dimensions of value</p><h2>Practical impact across the value chain.</h2></div><p>We describe impact carefully and do not publish unsupported environmental savings or employment figures.</p></div><div class="impact-pillars"><article class="impact-pillar"><span>Environmental</span><h3>Productive resource use</h3><p>Processing creates an alternative use for cassava peels that might otherwise accumulate around processing locations.</p></article><article class="impact-pillar"><span>Economic</span><h3>Commercial value from waste</h3><p>Drying and milling turn an agricultural by-product into products that can participate in feed value chains.</p></article><article class="impact-pillar"><span>Social</span><h3>Opportunity in operating communities</h3><p>Collection and processing activities can support gainful work and participation for young people in the communities where we operate.</p></article></div></div></section>
    <section class="section"><div class="container intro-grid"><div><p class="eyebrow">How we approach sustainability</p><h2>Specific, useful and accountable.</h2></div><div class="principle-list"><article><h3>Use resources purposefully</h3><p>Look for commercial applications for agricultural materials that are being underused.</p></article><article><h3>Build local capability</h3><p>Create opportunities for people to participate in collection, handling and processing activities.</p></article><article><h3>Serve real demand</h3><p>Connect processed products with genuine feed-sector and agricultural requirements.</p></article><article><h3>Communicate honestly</h3><p>Avoid unsupported claims and provide current product information directly to buyers.</p></article></div></div></section>
    ${faqSection("Circular agriculture and community value.", pageFaqs.impact)}
    ${band("Build value with us.", "Talk to our team about cassava peel supply, processed products, partnerships or community-based opportunities.")}` }),

  "faq.html": page({ active: "faq", meta: { title: "Agribusiness & Product FAQs | Patrick Stone Ventures", description: "Answers about Patrick Stone Ventures, cassava peel processing, agricultural commodities, bulk orders, delivery, quality and greenhouse solutions in Nigeria.", path: "faq.html", faqs: allFaqs }, main: `
    ${hero("Knowledge centre", "Frequently asked questions.", "Clear answers about our company, cassava processing, agricultural commodities, commercial orders, quality and greenhouse solutions.", "cassava-processing.webp")}
    <section class="section faq-directory"><div class="container"><div class="section-heading"><div><p class="eyebrow">Browse by topic</p><h2>Information for buyers and partners.</h2></div><p>These answers provide general guidance. Current product specifications, availability, pricing and commercial terms are confirmed for each enquiry.</p></div><nav class="faq-topic-nav" aria-label="FAQ topics">${faqGroups.map(group => `<a href="#${group.id}">${group.title}</a>`).join("")}</nav>${faqGroups.map(group => `<section class="faq-group" id="${group.id}"><div class="faq-group-heading"><p class="eyebrow">FAQ topic</p><h2>${group.title}</h2></div>${faqList(group.items)}</section>`).join("")}</div></section>
    ${band("Still have a question?", "Tell our team what product, service or project information you need.")}` }),

  "contact.html": page({ active: "contact", meta: { title: "Contact Patrick Stone Ventures | Lagos, Nigeria", description: "Contact Patrick Stone Ventures for cassava products, commodity supply, greenhouse solutions and agribusiness partnerships.", path: "contact.html", faqs: pageFaqs.contact }, main: `
    ${hero("Contact us", "Let’s discuss your requirements.", "Talk to our team about product supply, commodity sourcing, greenhouse infrastructure or agricultural partnerships.", "hero-cassava-processing.webp")}
    <section class="section"><div class="container contact-grid"><div class="contact-intro"><p class="eyebrow">Get in touch</p><h2>Start a commercial conversation.</h2><p>Share the product, service or partnership requirement you would like to discuss.</p><div class="contact-card"><h3>Office</h3><p>7 Ibiyinka Olorunbe Street<br>Victoria Island, Lagos<br>Nigeria</p></div><div class="contact-card"><h3>Phone</h3><p><a href="tel:+2348167525393">+234 816 752 5393</a></p></div><div class="contact-card"><h3>Email</h3><p><a href="mailto:sales@patrickstoneventures.com.ng">sales@patrickstoneventures.com.ng</a></p></div></div>
      <form class="quote-form contact-form" action="#" method="post" data-static-form><h2>Send an enquiry.</h2><p class="intro-copy">Complete the form and connect it to your preferred static-form provider before launch.</p><div class="form-grid"><label>Full name<input type="text" name="name" autocomplete="name" required></label><label>Company<input type="text" name="company" autocomplete="organization"></label><label>Email<input type="email" name="email" autocomplete="email" required></label><label>Phone<input type="tel" name="phone" autocomplete="tel"></label><label>Enquiry type<select name="enquiry_type" required><option value="">Select an option</option><option>Cassava Products</option><option>Commodity Trading</option><option>Greenhouse Solutions</option><option>Partnership</option><option>General Enquiry</option></select></label><label>Product interested in<input type="text" name="product"></label></div><label>Message<textarea name="message" rows="6" required></textarea></label><button class="button button-dark" type="submit">Send enquiry</button><p class="form-note" aria-live="polite" data-form-note></p></form></div></section>
    ${faqSection("Before you enquire.", pageFaqs.contact)}
    <iframe class="map-frame" title="Patrick Stone Ventures office area in Victoria Island, Lagos" src="https://www.google.com/maps?q=7%20Ibiyinka%20Olorunbe%20Street%2C%20Victoria%20Island%2C%20Lagos%2C%20Nigeria&amp;output=embed" width="100%" height="410" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>` })
};

const productFaqs = product => {
  const specific = {
    "cassava-peel-flour": ["What is cassava peel flour?", "Is cassava peel flour suitable for poultry feed?", "Can cassava peel flour be used in fish feed?", "Where can I buy cassava peel flour in Nigeria?"],
    "cassava-peel-grits": ["What are cassava peel grits?", "What is the difference between cassava peel flour and cassava peel grits?", "Where can I buy cassava peel grits in Nigeria?", "Does Patrick Stone Ventures provide laboratory specifications for cassava peel products?"],
    "cassava-flour": ["Does Patrick Stone Ventures supply cassava flour?", "Does Patrick Stone Ventures supply agricultural commodities in bulk?", "Can buyers request product samples or specifications?"],
    "cassava-starch": ["Does Patrick Stone Ventures supply cassava starch?", "Does Patrick Stone Ventures supply agricultural commodities in bulk?", "Can buyers request product samples or specifications?"],
    "soybean-cake": ["Does Patrick Stone Ventures supply soybean cake in Nigeria?", "Where can I buy soybean cake in bulk in Nigeria?", "How much does soybean cake cost in Nigeria?", "Can buyers request product samples or specifications?"],
    "palm-kernel-cake": ["Does Patrick Stone Ventures supply palm kernel cake?", "Does Patrick Stone Ventures supply agricultural commodities in bulk?", "Can buyers request product samples or specifications?"],
    maize: ["Does Patrick Stone Ventures supply maize in Nigeria?", "Does Patrick Stone Ventures supply agricultural commodities in bulk?", "Does Patrick Stone Ventures deliver agricultural commodities?"]
  };
  return findFaqs(...specific[product.slug]);
};

for (const product of products) {
  const related = products.filter(p => p.slug !== product.slug).slice(0, 3);
  const faqs = productFaqs(product);
  pages[`product-${product.slug}.html`] = page({ meta: { title: `${product.name} Supplier Nigeria | Patrick Stone Ventures`, description: `${product.description} Request current specifications, packaging options and supply availability.`, path: `product-${product.slug}.html`, image: product.image, schema: "Product", faqs }, main: `
    <section class="product-hero"><div class="product-hero-grid"><div class="product-hero-image"><img src="assets/images/${product.image}" alt="${product.name}"></div><div class="product-hero-copy"><div class="breadcrumb"><a href="index.html">Home</a> / <a href="products.html">Products</a> / ${product.name}</div><p class="eyebrow eyebrow-light">${product.categoryLabel}</p><h1>${product.name}</h1><p>${product.description}</p><div class="product-meta"><div><span>Supply market</span><strong>Nigeria and regional enquiries</strong></div><div><span>Specifications</span><strong>Available on request</strong></div></div><div class="button-row"><button class="button" data-quote-open data-product="${product.name}">Request bulk quote</button><a class="button button-outline-light" href="contact.html">Contact sales</a></div></div></div></section>
    <section class="section"><div class="container intro-grid"><div><p class="eyebrow">Product overview</p><h2>Commercial supply for agricultural value chains.</h2></div><div class="intro-copy"><p class="lead">${product.overview}</p><table class="spec-table"><tbody><tr><th>Current specification</th><td>Available on request</td></tr><tr><th>Packaging options</th><td>Confirm with our sales team</td></tr><tr><th>Order quantity</th><td>Discuss your requirement</td></tr><tr><th>Delivery</th><td>Subject to location and current availability</td></tr></tbody></table></div></div></section>
    <section class="section value-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">Applications and buyers</p><h2>Is this product right for you?</h2></div><p>Final suitability should be assessed against your process, formulation and required specification.</p></div><div class="use-grid">${product.applications.map((a, i) => `<article class="use-card"><span>0${i+1}</span><h3>${a}</h3><p>Contact our team to discuss the intended application and current product specification.</p></article>`).join("")}</div><div class="statement" style="margin-top:24px">Typical customers include ${product.customers.join(", ").toLowerCase()}.</div></div></section>
    <section class="section"><div class="container"><div class="section-heading"><div><p class="eyebrow">Related products</p><h2>Continue exploring.</h2></div></div><div class="catalog-grid">${related.map(p => `<article class="product-card"><a class="product-image" href="product-${p.slug}.html"><img src="assets/images/${p.image}" alt="${p.name}" loading="lazy"><span>${p.categoryLabel}</span></a><div class="product-body"><h3><a href="product-${p.slug}.html">${p.name}</a></h3><p>${p.description}</p><div><a class="text-link" href="product-${p.slug}.html">View product →</a></div></div></article>`).join("")}</div></div></section>
    ${faqSection(`${product.name} supply.`, faqs)}
    ${band(`Request a ${product.name.toLowerCase()} quote.`, "Share your estimated quantity, delivery location and timing with our sales team.", product.name)}` });
}

for (const [filename, html] of Object.entries(pages)) writeFileSync(new URL(`../${filename}`, import.meta.url), html);
console.log(`Built ${Object.keys(pages).length} static pages.`);
